version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_FLASH_ATTENTION=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-kane-net

  ai-agent:
    build: .
    container_name: ai-kane-agent
    ports:
      - "8000:8000" # ПРОБРАСЫВАЕМ ПОРТ ДЛЯ VS CODE
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434/v1/chat/completions
      - MODEL_NAME=llama3.1:8b
    depends_on:
      - ollama
    networks:
      - ai-kane-net

volumes:
  ollama_storage:

networks:
  ai-kane-net:
    driver: bridge