[pytest]
# Автоматически обрабатывать все async def функции без написания маркеров в коде
asyncio_mode = auto

# Задаем дефолтную область видимости для циклов событий (совместимо с asyncio-1.4.0)
asyncio_default_test_loop_scope = function

# Подавляем лишние системные предупреждения сторонних библиотек в консоли
filterwarnings =
    ignore::pytest.PytestDeprecationWarning
    ignore::DeprecationWarning:starlette.*